### ISSUE TITLE
Inclusion of Windows Colors

### ISSUE THREAD

**Issue by BrandonKMLee** [meodai/color-names#102]
For reference https://camo.githubusercontent.com/fc21ad30d1a86b7a5ba896f4a0d374ffd4de3fec1d370a365a9235498210cc02/687474703a2f2f692e696d6775722e636f6d2f316c444354764b2e706e67

**Comment by meodai** [comment]
@BrandonKMLee I am in the process of importing them: https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.colors?view=net-5.0

But 95% are already in the list.

**Comment by meodai** [comment]
Thank you for your suggestion @BrandonKMLee the missing names are now in.
