### ISSUE TITLE
Inclusion of Japanese Colors

### ISSUE THREAD

**Issue by BrandonKMLee** [meodai/color-names#104]
Main sources being
- https://www.colordic.org/w
- https://nipponcolors.com/
- https://www.wikiwand.com/en/Traditional_colors_of_Japan
- http://kidorakujapan.com/know/others_color.html
- https://iwabijin.wordpress.com/japanese-traditional-colors/
- https://www.stefanimhoff.de/traditional-colors-of-japan/
- https://simplicable.com/new/japanese-colors

Cross-referencing https://github.com/colorjs/color-namer/issues/15

**Comment by meodai** [comment]
they are all in already.
