### ISSUE TITLE
Add to dist colornames.bestof.json without # symbol

### ISSUE THREAD

**Issue by phlqp** [meodai/color-names#109]
Please add a file to dist, similar to colornames.bestof.json, without # symbol
Example: 
[{"name":"100 Mph","hex":"c93f38"},{"name":"20000 Leagues Under the Sea","hex":"191970"}, ...]

Thanks

**Comment by meodai** [comment]
@phlqp can you give me more context? Most people need it with the #.

**Comment by phlqp** [comment]
My app's database uses HEX, the primary key, it is only 6 chars, I must remove # symbol before operates

**Comment by meodai** [comment]
This sounds more like something you should solve in your app not really an Issue of that package. 

I would a) preprocess the list or b) write an import script.I will not do this change. Since it would be a breaking change to all the other apps that use that list.

**Comment by phlqp** [comment]
Can you add a new file?
