### ISSUE TITLE
Add example using “nearest color”

### ISSUE THREAD

**Issue by getflourish** [meodai/color-names#11]
The demo on CodePen is great as it takes any color input and returns a name, perfect!

But when I first tried the example code from this repo, I was disappointed, because I didn’t realize, that the code was only returning a color name for exact matches. 

I then noticed that the demo was using `nearest-color.js`. Maybe you can consider adding an example to the README. 

At least, this is how I’m using it now. Thanks! :)

```
// import color name list
let namedColors = require('color-name-list');

// transform color array to map
let colors = {};

namedColors.forEach(function (color) {
  colors[color.name] = color.hex
})

// define nearestColor
let nearestColor = require('nearest-color').from(colors);

// get color
var namedColor = nearestColor("#ffcc00)
```

**Comment by meodai** [comment]
@getflourish Thanks for the feedback. Sine its only a list. I wanted to keep the example as vanilla as possible. But I should probably add one section called: JS Example; Finding an color by exact hex value or name, and a second example called, finding a name for every color? What do you think?

**Comment by meodai** [comment]
@getflourish see ce9be8a let me know if this works for you

**Comment by getflourish** [comment]
Love it. I think the API does a great job at doing exactly that. But for the cases when it’s not an option, the example explains how to DIY :)

**Comment by meodai** [comment]
cool then let me close that issue. I wonder if we should use the wiki pages. Since there is a lot to tell about it :D
