### ISSUE TITLE
Color Groups

### ISSUE THREAD

**Issue by mariohmol** [meodai/color-names#119]
Hi,

is anyway to pick up a list of colors based on groups?

Like, all the colors for Wikipedia link? or all colors for a catalog XYZ?

thanks

**Comment by meodai** [comment]
@mariohmol its not. Since there was a lot of manual merging. Lots of lists have the same color with different names or same names for different colors. Lots of manual merging was involved. So it would be quite hard to pull off, even if the information was still around
