### ISSUE TITLE
Examples In README Do Not Work

### ISSUE THREAD

**Issue by ChocDoc21** [meodai/color-names#125]
I am trying to test out the library.

I wanted to test out the "nearest-colors" example but it throws an error: https://codesandbox.io/s/cranky-shape-o6kwi?file=/src/App.js

Then I wanted to test out "exact color", same error: https://codesandbox.io/s/peaceful-cache-vv5kh?file=/src/App.js

![Capture](https://user-images.githubusercontent.com/96153176/146098859-6774dcfa-ff23-4f58-8733-90d5d0bcd416.PNG)

What am i doing wrong?

**Comment by meodai** [comment]
https://codepen.io/meodai/pen/d67f5106ce1b0a6cfe563f12a95ee1cd
