### ISSUE TITLE
Fix typo "sematnic".

### ISSUE THREAD

**Issue by hellowollen** [meodai/color-names#136]
I found a typo at "[Git](https://github.com/meodai/color-names/blob/284c9b5dfbaf48214f5353641b0949c6f9042af3/CONTRIBUTING.md#git)" in [CONTRIBUTING.md](https://github.com/meodai/color-names/blob/284c9b5dfbaf48214f5353641b0949c6f9042af3/CONTRIBUTING.md).

```md
- We use automated sematnic versioning using (...)
```

should be fixed to

```md
- We use automated semantic versioning using (...)
```

Note how the fourth word "sematnic" is now correctly written as "semantic".

**Comment by meodai** [comment]
@hellowollen thanks for that! it was addressed in 7016b3c9566fd9a24431fae059fcd19f4b133b92
