### ISSUE TITLE
Add Chinese traditional colors

### ISSUE THREAD

**Issue by ItMarki** [meodai/color-names#138]
Hello. I'm new to this, so I don't really understand the standard procedure.

I want to add Chinese traditional colors documented in a book called _Traditional Colors of China: Color Aesthetics in the Forbidden City_ (中国传统色：故宫里的色彩美学), but I don't really want to use node.js, so I'm submitting [my .csv file](https://github.com/ItMarki/files/blob/main/colornames.csv) here.

There should be [384 new colors](https://github.com/ItMarki/files/blob/main/newcolors.csv) in that file. (Ignore the first line)

Edit: I also found a website that lists even more Chinese traditional colors [here](http://zhongguose.com/), though I haven't sorted them out yet.

**Comment by meodai** [comment]
@ItMarki thanks for your contribution! Would It be possible to add a row with the Chinese characters as well? Would love to add it to: https://github.com/meodai/color-name-lists

**Comment by ItMarki** [comment]
Thank you for asking. [It should be here](https://github.com/ItMarki/files/blob/main/newcolorsandnames.csv).

**Comment by meodai** [comment]
https://user-images.githubusercontent.com/608386/205953377-87f3e44f-e83c-4b08-b25d-7c43f20a4f18.mov

**Comment by meodai** [comment]
https://user-images.githubusercontent.com/608386/205958175-2c93cb77-59e6-4276-94ec-6cc1ee1bff72.mov

**Comment by meodai** [comment]
@ItMarki thanks so much
