### ISSUE TITLE
get some color names from https://colornames.org/

### ISSUE THREAD

**Issue by LouisyDD** [meodai/color-names#144]
https://colornames.org/

**Comment by meodai** [comment]
Most of them are pretty bad in quality. Since its not really possible to sort them by votes, I have no idea how this could be done easily.

**Comment by LouisyDD** [comment]
just grab some of them

**Comment by meodai** [comment]
feel free to propose some, just sure they follow the [contribution rules](https://github.com/meodai/color-names/blob/master/CONTRIBUTING.md).

**Comment by LouisyDD** [comment]
{"hexCode":"22e998","name":"Easter Green"}
{"hexCode":"e07099","name":"Miami Pink"}
{"hexCode":"a85af2","name":"Airolg"}
{"hexCode":"9995c6","name":"Mora Yogurt"}
{"hexCode":"6d5129","name":"Kommetjie Tented Camp"}
{"hexCode":"c56d7a","name":"Blossom Tree"}
{"hexCode":"914cf5","name":"Aphmaus Bow"}

**Comment by meodai** [comment]
- Easter Green, is already a color name.
- Miami Pink will make it into the next release.
- Not sure why Airolg should be a color? Its a given name as far as I know?
- Blossom Tree will make it in, even if we have Sakura and Cherry Blossom already.
- Aphmaus Bow will not make it in.

Please make sure to read and follow the [contribution rules](https://github.com/meodai/color-names/blob/master/CONTRIBUTING.md) if you intend making more proposals.

Thanks for you contribution.
