### ISSUE TITLE
When passing in a hex code to get color name, the hex code needs to be in lower case. So it would be better to accept uppercase too

### ISSUE THREAD

**Issue by gibtang** [meodai/color-names#159]
Example, this works

let someColor = namedColors.find(color => color.hex === '#ffffff');
console.log(someColor.name); // => white

But

let someColor = namedColors.find(color => color.hex === '#FFFFFF');
console.log(someColor.name); //does not work

Following Postel's Law, it would be good to accept uppercase hexcodes too. I can file a PR for this if needed

**Comment by meodai** [comment]
hey @gibtang thanks for reporting that. This repository only contains the names, this is example code to help people implement it. I don't need it to be robust, just get the point across. But I guess adding a simple `.toLowerCase()` in the example does not hurt too much.
