### ISSUE TITLE
Colour Lovers?

### ISSUE THREAD

**Issue by scottw-kr** [meodai/color-names#164]
Is it unethical to source from www.colourlovers.com? They have 10M user generated colors and I'm sure you could pull the top 1,000 or something as the colors have metadata about views and inclusion in palettes.

**Comment by meodai** [comment]
thanks! @scottw-kr some of the names are already in, but the license for the palettes / colors on colourlovers are too restrictive for us. We use MIT, that basically allows you to do anything you want with it. Colourlovers restricts commercial use and forces attribution.
