### ISSUE TITLE
Name collision + typo

### ISSUE THREAD

**Issue by galopin** [meodai/color-names#166]
Howdy,

I'd like to report a name collision in the latest CSV [data file](https://github.com/meodai/color-names/blob/e03ca0623d2c3e62db6a21ba4291b87e1ca05aa8/src/colornames.csv#L20924-L20927):

```
Potter's Clay,#a64826,
; line #20924
```

vs.

```
Potter’s Clay,#bfa298,
; line #20926
```

The reason it went undetected is because the first occurrence contains a straight single quote (`'`) while the second contains an apostrophe (`’`).

Also there is a typo nearby:

```
Potters Pot,#845c40,
; line #20927
```

IMHO, it should read:

```
Potter's Pot,#845c40,
```

I'm not advocating the systematic use of curly apostrophes but this could be an improvement.

Please see [Apostrophes, make sure they’re curly and point downward](https://practicaltypography.com/apostrophes.html) for further reference…

**Comment by meodai** [comment]
@galopin thanks so much for catching this, it was addressed in 6f14195212a8c2ab93e419d4cd061155819d2847. "Potter's Pot" will be fixed in the next release! (I will close the issue when its released)
