### ISSUE TITLE
Yet another name collision

### ISSUE THREAD

**Issue by galopin** [meodai/color-names#167]
Ahoy,

I'd like to report another name collision in the latest CSV [data file](https://github.com/meodai/color-names/blob/16c767ca8cc5814929a510428d5d985c74c17c68/src/colornames.csv#L13557-L13558):

```
It’s a Girl,#de95ae,
; line #13557
```

vs.

```
It’s A Girl!,#ffdae2,
; line #13558
```

The problem is a bit different this time: capitalization and punctuation mark.

**Comment by meodai** [comment]
@galopin thanks! it was fixed!
