### ISSUE TITLE
Bad color name for light red and light blue

### ISSUE THREAD

**Issue by vvcdev** [meodai/color-names#170]
Both light blue and light red are way to bright (light red is like an extremely pale pink)

https://colorhub.art/color/%23add8e6 | I suggest turning it into | [#ADD8E6](https://colorhub.art/color/%23ADD8E6)

https://colorhub.art/color/%23f3d3d9 | I suggest turning it into [#FF7F7F](https://colorhub.art/color/%23FF7F7F)

If possible do the same with other light colors those are just the ones I came across

**Comment by meodai** [comment]
Hey, that is a good suggestion, thanks for reporting it. I will work on it next time I do something else.
