### ISSUE TITLE
Spelling error in README.md

### ISSUE THREAD

**Issue by gaurav10000** [meodai/color-names#172]
There is an spelling error in the README.md file, I can fix that.

**Comment by meodai** [comment]
@gaurav10000 what's wrong?

**Comment by gaurav10000** [comment]
Inside README.md in API section it is written as: "API Exaple Call Usage" which should be "API Example Call Usage" and one more thing I am very new to open source contributions, can you please let me fix this, this will be my first contribution.

**Comment by meodai** [comment]
Sure, let me know if you need help we can set up a quick call.

**Comment by gaurav10000** [comment]
Thank u very much, I will surely call you.

**Comment by gaurav10000** [comment]
I am unable to find anyone with username meodai on discord.

**Comment by meodai** [comment]
meodai#5245

**Comment by gaurav10000** [comment]
I still didn't got any results for meodai#5245, any other social media or any other way to connect on discord?? If you don't mind please send "hi" to __madarauchiha_ , this is my discord username.

**Comment by gaurav10000** [comment]
hey meodai, I messaged you on discord. I made a pull request 4-5 days back, can you check that out, please let me know if I did something wrong,I would love to work more on this project.

**Comment by meodai** [comment]
fixed in #173, thanks for your contribution
