### ISSUE TITLE
[issue] `namedColors.find` isn't a function?

### ISSUE THREAD

**Issue by MordechaiHadad** [meodai/color-names#177]
I am using this lib and trying to get a color's name with `Array.find` but my browser console shows that `namedColors` import doesn't have the find function, why?

Code Example:
https://github.com/MordechaiHadad/tints-and-shades-generator/blob/master/src/routes/%2Bpage.svelte#L26

**Comment by meodai** [comment]
Have you console logged namedColors?

**Comment by MordechaiHadad** [comment]
I did the result was:
```
Object { colorNameList: (30241) […] }
​
colorNameList: Array(30241) [ {…}, {…}, {…}, … ]
​
<prototype>: Object { … }
```

**Comment by meodai** [comment]
@MordechaiHadad by the way you can also use the rest API so you don't have to carry a huge file in your codebase:

```

https://api.color.pizza/v1/?values=ff0000,ff0000&list=bestOf&noduplicates=true

```

https://github.com/meodai/color-name-api

**Comment by meodai** [comment]
@MordechaiHadad https://github.com/meodai/color-names/commit/ca8f60ca1ae25eb5c286206cbe40229a81bbd0f3
