### ISSUE TITLE
Ability to sort color names by color, not by name.

### ISSUE THREAD

**Issue by tj-commits** [meodai/color-names#182]
Along with the colors being alphabetical, also I think there should be a feature to sort in order by hue, maybe by converting colors to HSL

**Comment by meodai** [comment]
Hey. this is just a static list of colors. are you talking about the API? Help me understand where you are coming from and what you are trying to do.

**Comment by tj-commits** [comment]
I am talking about the user interface at meodai.github.io/color-names/

I think you should be able to sort by hue.

**Comment by meodai** [comment]
I have tried more than once to get nice color sorting. Due to its 3 dimensional nature, its pretty hard to sort colors nicely in a 1d list...

My explorations.
https://codepen.io/meodai/pen/mdpNJQQ

https://codepen.io/meodai/details/yLgzORo
