### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by fearganni** [meodai/color-names#184]
Anyway to add typescript support, either by using `@types/...` or directly within this package?
-- Very awesome package otherwise!

**Comment by meodai** [comment]
an enum of all the names? :D

**Comment by fearganni** [comment]
> an enum of all the names? :D

Can't even remember why I made this issue, pretty sure you can just import the data as JSON into typescript.
Low IQ brain moment lmao, was probably a misconfiguration on my side at the time 🤣
