### ISSUE TITLE
Decolonizing Colour Names

### ISSUE THREAD

**Issue by bbogart** [meodai/color-names#185]
Hey all, wondering if anyone is working on or thinking about colonial baggage in colour name data-bases such as this. 

Specific issues that come to mind are colour names like "Kef* Lime" where the first word is a racial slur in South Africa (https://en.wikipedia.org/wiki/Kaffir_(racial_term)), "Gypsy" is also a racial slur against the Romani people (https://web.archive.org/web/20050205135317/http://www.utexas.edu/features/archive/2003/romani.html), imperialist words referring to whole regions regardless stereotyping the individual cultures, e.g. "Oriental" (https://www.weareresonate.com/2016/07/oriental-racist-term/) are issues. Even names like "Aladdin's feather" if referencing the Disney movie, become a problem due to Arab stereotyping (https://adc.org/arab-stereotypes-and-american-educators/), and colourism, e.g. a very pale person shade for "Naked Lady". 

Aside from this important issue, there are also just some issues of redundancy, e.g. "Heart Gold" vs "Heart of Gold", "Paperwhite" vs "Paper White", etc. 

Has anyone done an audit of the names checking for such issues?

**Comment by meodai** [comment]
Hey @bbogart thanks for bringing this up.

I do take care of that when new names are submitted. But there are many names that were imported from other lists. Whenever I came across a name that was racist or colonial I would remove it or find a replacement.

So I am very thankful for the ones spotted and will remove them immediately. 

Please submit other you find. I will open an other issue about redundancy. To keep things organised.

**Comment by someguy9** [comment]
Some names that may be problematic (note I generated this with AI to scan the list)

---

1\. **Gypsy Red**  

   - **Hex Code:** #cc0001  

   - **Reason:** "Gypsy" is considered offensive to the Romani people.

2\. **Oriental Blue**  

   - **Hex Code:** #a59344  

   - **Reason:** "Oriental" is outdated and considered offensive.

3\. **Aladdin's Feather**  

   - **Hex Code:** #f4efee  

   - **Reason:** References to Disney's "Aladdin" may promote Arab stereotyping.

4\. **Naked Lady**  

   - **Hex Code:** #ffe8dd  

   - **Reason:** Refers to skin tone in a potentially offensive way.

5\. **Naked Noodle**  

   - **Hex Code:** #f7cb6e  

   - **Reason:** Could be interpreted as referring to skin tone.

6\. **Bloodthirsty Beige**  

   - **Hex Code:** #f8d7d0  

   - **Reason:** Implies a beige skin tone is bloodthirsty.

7\. **Addo Skin**  

   - **Hex Code:** #585d58  

   - **Reason:** Possibly references a specific ethnicity's skin tone.

8\. **Black Is Beautiful**  

   - **Hex Code:** #552222  

   - **Reason:** While intended to be positive, this directly ties a color to a specific race and could be seen as reductive.

9\. **Ghetto Fabulous**  

   - **Hex Code:** #f0e8d5  

   - **Reason:** This is a slang term often associated with negative stereotypes about Black culture.

10\. **Communist**  

    - **Hex Code:** #cc0000  

    - **Reason:** Associates a color with a political ideology, which could be considered insensitive.

11\. **Holy Ghost**  

    - **Hex Code:** #efe9e6  

    - **Reason:** Religious connotations, may not be appropriate for a general audience.

12\. **Holy Water**  

    - **Hex Code:** #466e77  

    - **Reason:** Religious connotations, may not be appropriate for a general audience.

13\. **Holy White**  

    - **Hex Code:** #f5f5dc  

    - **Reason:** Religious connotations, may not be appropriate for a general audience.

14\. **Hindu Lotus**  

    - **Hex Code:** #ee4d83  

    - **Reason:** Religious connotations, may not be appropriate for a general audience.

15\. **Islam Green**  

    - **Hex Code:** #009900  

    - **Reason:** Associates a color with a religion, potentially insensitive.

16\. **Voodoo**  

    - **Hex Code:** #443240  

    - **Reason:** Possibly perpetuates harmful stereotypes about Vodun, a religion with African origins.

17\. **Canadian Voodoo Grey**  

    - **Hex Code:** #b8b7a3  

    - **Reason:** Possibly perpetuates harmful stereotypes about Vodun, a religion with African origins.

18\. **Colonial White**  

    - **Hex Code:** #e8e5e3  

    - **Reason:** Refers to a specific period of history marked by colonialism, potentially triggering.

19\. **British Racing Green**  

    - **Hex Code:** #05480d  

    - **Reason:** Refers to a specific nation, which might not be inclusive to a global audience.

20\. **Bombay**  

    - **Hex Code:** #aeaead  

    - **Reason:** Former colonial name of Mumbai, may be considered outdated.

**Comment by meodai** [comment]
@someguy9 

Thanks for this:

(1,2,3,4) is gone in (https://github.com/meodai/color-names/commit/49d6e9f4b33584e15e05eda6d70d184e82eb0391) 
(8,7,20,17) is going to be removed
(5) Naked Noodle: is funny and does not refer to a skin color
(6) Bloodthirsty Beige: refers to the beige having a hint of red
(19) is fine

Not sure about:
18. 15, 14, 10, 9

Please help me with these

**Comment by meodai** [comment]
I will close this, just open a new one, or comment below if there is more. Thanks!
