### ISSUE TITLE
Build breaking using vue 3 + vite

### ISSUE THREAD

**Issue by ericuldall** [meodai/color-names#189]
Error: 'colorNameList' is not exported by node_modules/color-name-list/dist/colornames.umd.js

any ideas? Using node 20 to build

**Comment by meodai** [comment]
`
import colorNameList from "color-name-list/dist/colornames.umd.js";

console.log(colorNameList);
`

works for me in node 20 after having installed `color-name-list`

**Comment by ericuldall** [comment]
I've tried both
```
Error: 'default' is not exported by node_modules/color-name-list/dist/colornames.umd.js
```

**Comment by ericuldall** [comment]
```import * as colorNameList``` works locally in dev mode but get a type error when deploying a production build

**Comment by ericuldall** [comment]
For now I just converted the csv to json and imported it as a local file. I think it would be great if there was ESM support on this package as that seems to be preferred for the newer build tools

**Comment by meodai** [comment]
@ericuldall 82731ea1c7c3afa18f2993b8254126601d3ef5aa should address your issue

`import {colornames} from `color-name-list`
or
`import {colornames} from `color-name-list/bestof` etc..

is the new way to go
