### ISSUE TITLE
Find a way to import military paint references

### ISSUE THREAD

**Issue by meodai** [meodai/color-names#21]
http://paintref.com/cgi-bin/colorcodedisplay.cgi?manuf=Military&gncl=brown&con=mc&rows=50

Only the unique names, we don't need 19830123 colors calld "brown" :D

**Comment by SgiobairOg** [comment]
Have scraped the page to JSON (attached). I believe I have only the uniquely named colors from the five-page list of military colors. The original list was 876, de-duplication took it down to 104 unique colors. 


[paintRefMilitary_NoDup.json.zip](https://github.com/meodai/color-names/files/1311954/paintRefMilitary_NoDup.json.zip)

**Comment by meodai** [comment]
@SgiobairOg thanks is imported it to the google docs.
