### ISSUE TITLE
Create an installable GEM

### ISSUE THREAD

**Issue by meodai** [meodai/color-names#22]
gem install color-names would be kinda awesome.

**Comment by meodai** [comment]
It would make it easier to install on ruby projects. I'm just not sure how to publish a GEM that only consists of non ruby files.

**Comment by armahillo** [comment]
The gem would probably need to have the `color-names.csv` and a ruby script that accepts a color value (whatever kind) and returns the appropriate name from that value.

**Comment by meodai** [comment]
Does not look like anyone has a need for that ;)
