### ISSUE TITLE
Cannot find module 'color-name-list'

### ISSUE THREAD

**Issue by maracuja-juice** [meodai/color-names#35]
I want to use this repo in a CLI made with TypeScript so I went ahead and added it via yarn:
`yarn add color-name-list`

Unfortunately when trying to use it I get the error:
`Cannot find module color-name-list`
I import it in the following way:
`import namedColors from 'color-name-list';`

I don't think it's about missing typescript types, that would be a different error.
Do you have an idea what could be causing this?

**Comment by meodai** [comment]
thats odd. Can you share your code with me?

**Comment by maracuja-juice** [comment]
Yes, I'll as soon as I get back to it

**Comment by meodai** [comment]
I think it has something to do with your setup. I tired it with a on a blank JS with nothing but node 9.0 and it works just fine. Il reopen the issue, it it turns out to be an issue with the JSON file

**Comment by maracuja-juice** [comment]
Yeah probably I am doing something wrong, need to try again sometime!
