### ISSUE TITLE
Generate ICC color profile

### ISSUE THREAD

**Issue by Crissov** [meodai/color-names#44]
[Apparently](https://github.com/w3c/csswg-drafts/issues/817#issuecomment-296172624) there is a _NamedColor profile_ `nmcl` in ISO 15076-1, vulgo ICC. I'm not sure how widespread its support and use are or how simple it would be to generate (e.g. with [Little CMS](/mm2/Little-CMS/)), but it _seems_ like a useful addition to me.

**Comment by Crissov** [comment]
Honestly, I have no idea. Little CMS has a [tutorial on the matter](http://www.littlecms.com/LittleCMS2.9%20tutorial.pdf#page=19), but that does not help much, at least for me.

**Comment by meodai** [comment]
don't think this is gonna happen, nor that useful
