### ISSUE TITLE
Add 21k names from colornames.org

### ISSUE THREAD

**Issue by hugovk** [meodai/color-names#48]
https://colornames.org is a "collaborative effort to name every color in the RGB/web space".

They currently have 21,010 colour names and the data is downloadable under CC0 1.0 Universal (CC0 1.0) Public Domain Dedication.

**Comment by meodai** [comment]
Hallo @hugovk awesome, I did not know this project! 

But sadly the quality of the names is poor + There are quite some names that make no sense to me. 

```
000000,Black,1
000001,It's Still Basically Black,0.143
000002,Blacker,0.048
000003,Not Really Black,0.19
000004,Blackerererer,0.048
```

Also there are quite a lot of protected brandnames like Dell, Microsoft etc...

Can you think of a good way to filter those out?

**Comment by hugovk** [comment]
They look like good names to me! :)

Something like https://github.com/dariusk/wordfilter/ with a custom word filter could be used for filtering.

**Comment by meodai** [comment]
I have decided to no add the color names from colornames.org looks like they have encoding problems äöü.. characters are missing + I find the quality of the names to be pretty bad

**Comment by tj-commits** [comment]
I don't like colornames.org Black #000000 is now voted called "Dude Who Turned The Lights Off"

bad name lmao I mean it is made by the community and silly names allowed
