### ISSUE TITLE
Import names from http://people.csail.mit.edu/jaffer/Color/Dictionaries

### ISSUE THREAD

**Issue by meodai** [meodai/color-names#5]
http://people.csail.mit.edu/jaffer/Color/Dictionaries

Tons of names list, evaluate and import lists.

**Comment by SgiobairOg** [comment]
Any guidance for how you want the lists evaluated?

**Comment by meodai** [comment]
@SgiobairOg I only merge in names that are not already in the list. So only unique names. And if two colors have the same names but different hex values. I come up with a new name. I usually do this in the google spreadsheet I've done. But I am bulding a node toolset to make things a bit easier

**Comment by csandman** [comment]
@meodai  Are these all imported or would you still like help with them?

**Comment by meodai** [comment]
@csandman no they are not imported yet. We are still looking for help.
