### ISSUE TITLE
New project using this list: https://hexy.io/

### ISSUE THREAD

**Issue by joshuaiz** [meodai/color-names#55]
Hello,

Thank you so much for compiling and updating this list. Don't mean to impose but wanted to let you know about a project I built using your amazing color list: https://hexy.io/

I've been wanting a site with a massive amount of colors to browse and never found one I really liked so I built one myself. I couldn't have done it without this list so thank you again.

With the site you can browse all named colors from your list but also get info on any color including harmonies, color spaces, nearest named color, etc. In addition, you can save any color to Favorites and export your Favorites to an editable PDF. Hexy.io is great for exploring, creating palettes, and discovering new colors.

GitHub repo for the project is here: https://github.com/joshuaiz/hexy

This is an early alpha for the site so will be adding more features in the coming weeks including .svg export, accounts, saved palettes, and more.

I've given this project a shout out but if you'd like to be referenced differently or more prominently, by all means let me know.

**Comment by meodai** [comment]
Hey man! I know your project existed, your project is listed in the dependencies. 
Great app, i gonna close the issue thought since its not really something actionable about your message. Don't hesitate to message me on twitter https://twitter.com/meodai or anywhere else basically.

**Comment by meodai** [comment]
But we can still chit chat here :D @joshuaiz I'm kinda impressed that the scroll is so smooth even though there are so many items in the dom. The HTML color export color-names is super slow...

**Comment by joshuaiz** [comment]
The smooth scrolling is just css on the html element: `html { scroll-behavior: smooth; }` :) but the site is all React.

In the first iteration of the site, I had a page with *all* 17K colors and it was a bit slow to load but once all the colors were loaded, it was smooth to scroll through. I may add that page back in.

All that said, the site is faster once built than on my local install thanks to Netlify.  

Also, every time you update the list, I download the json and swap out 'name' for 'n' and 'hex' for 'h' to condense it a bit and serve it locally. Since I'm doing so many color operations, I thought it would be better to do that than rely on an external file.

**Comment by meodai** [comment]
Oh why don't you use the api?

**Comment by joshuaiz** [comment]
I guess I could but I save 100K by condensing the json + serving it locally and that means the site will work even offline although I have to set up the service workers.

**Comment by meodai** [comment]
true that, maybe you I could ship an array version that would be even
smaller {colors:['name','#f00f00'],['bla','#123]}

**Comment by joshuaiz** [comment]
That's a good idea. Still, I'm surprised at the performance as it is. On my local install, entering search is a bit slow which can happen with React apps but on the built site there is no delay at all. 

I think I will add the page with all the colors - I mean why the hell not?

**Comment by meodai** [comment]
@joshuaiz something like that? https://github.com/meodai/color-names/blob/minified-json/dist/colornames.min.json removed the # to save even more space

**Comment by joshuaiz** [comment]
Ooooooh that could work I think - I'd have to do a major refactor though. On the docket for v2.0. 💯

**Comment by meodai** [comment]
@joshuaiz there you go https://github.com/meodai/color-names/pull/56
