### ISSUE TITLE
import some of the Apple system colours

### ISSUE THREAD

**Issue by sweetppro** [meodai/color-names#59]
These are directly from the Apple system color palette

#000000 - Black
#0433ff - Blue
#aa7942 - Brown
#00fdff - Cyan
#00f900 - Green
#ff40ff - Magenta
#ff9300 - Orange
#942192 - Purple
#ff2600 - Red
#fffb00 - Yellow
#ffffff - White

**Comment by meodai** [comment]
Hey! Thy are already all in: @sweetppro .

**Comment by sweetppro** [comment]
ah, I see they all have different names.
thx
:)
