### ISSUE TITLE
Import Paint Color names from https://encycolorpedia.com/

### ISSUE THREAD

**Issue by meodai** [meodai/color-names#60]
Not sure if we can find a good way to do it. I wrote an email to ask, if they are willing to share the source data.

**Comment by cheesits456** [comment]
I copied the front page's HTML source, then pretty-printed it and removed everything but the `<li>` tags containing the color data. I ended up with a 1,690 line file that looks like this:

![image](https://user-images.githubusercontent.com/35486894/91919717-b3ce5d80-ec7b-11ea-95cf-91480719cef6.png)

I'll write a script in a bit to parse out the data we want, then manually sanitize the names and make sure none are duplicates of the current list

**Comment by cheesits456** [comment]
Alright I started working on it now.

I used this regular expression to parse the HTML: [view on regexr.com](https://regexr.com/5b8sq)*

    /\t\t<li><a href=\/([0-9a-z]{6}) style=background-color:#\1(?:;color:#fff)?>(.*?)<br>#\1</a>/g

The RegExp defines two capture groups:

1. The six-character hexadecimal color code
2. The color name

Using Sublime Text's "Find and Replace" option, I used the stated RegExp as the "Find" field, and for "Replace" I used `$2,#$1,`. `$2` gets replaced with the second capture group (the color name), and `$1` gets replaced with the first (the hex code). The result is a properly formatted `CSV` file that matches the structure of the source `colornames.csv` file.

Now I need to sanitize the color names to be more descriptive with less words, and I also need to remove the HTML escape sequences. A couple examples of names that should be fixed are:

- `Dyestalk red (lit. the color from dying with the stalk of the beni plant) (Bengara-iro)`
- `Weathered bamboo (lit. &#34;sooty&#34;) (Susutake-iro)`

And then I'm gonna merge the file into `colornames.csv`, resolve any name or hex conflicts, and finally, when all is ready, I'll submit a PR.

<hr>

\* regexr.com has a bug that can cause the pattern to fail when initially loading it:

![image](https://user-images.githubusercontent.com/35486894/91931069-4af4de80-ec97-11ea-9b18-522334ffff57.png)

To make the pattern load properly, add any arbitrary character to the end of the regex pattern, then delete it. After that, it should load as intended

**Comment by cheesits456** [comment]
<p align="justify">I've run into something I'm not quite sure of - the following color definitions exist in the new data:</p>

```csv
Chinese Black,#141414,
Chinese Blue,#365194,
Chinese Bronze,#cd8032,
Chinese Brown,#ab381f,
Chinese Gold,#cc9900,
Chinese Green,#d0db61,
Chinese Orange,#f37042,
Chinese Pink,#de70a1,
Chinese Purple,#720b98,
Chinese Red,#aa381e,
Chinese Silver,#cccccc,
Chinese Violet,#856088,
Chinese White,#e2e5de,
Chinese Yellow,#ffb200,
```

<p align="justify">The way I interpret this is as a list of colors that are used in Chinese architecture. However, my concern is for situations where a user isn't presented with this full list of "Chinese" colors, but rather just a single value. In particular, the "Chinese Brown" and "Chinese Yellow" names could be interpreted as labels for skin color if no additional context is presented to the user. We can't predict all of the ways this API might be used, so that scenario is definitely a possibility.</p>

<p align="justify">So my question is: Should we come up with more specific names for these colors to clarify what they represent, should we simply remove the ones that could be misinterpreted, or am I possibly just overthinking this?</p>

**Comment by cheesits456** [comment]
<p align="justify">Welp, it's official: I'm dumb.</p>

<p align="justify">I finally finished manually sanitizing all ~1500 color names, then ran <code>npm run test</code>, only to realize that <i>all of these colors have already been added to the list.</i></p>

![Facepalm](https://pics.c456.xyz/facepalm/facepalm.jpg)

<p align="justify">At least I documented my process here, so other people might potentially learn from it ¯\_(ツ)_/¯ tbh even if the only thing they learn is to check if someone's already done what you're about to do, that's okay - evidently it's a mistake that even experienced developers make :P</p>

_In my defence, I was low on sleep when I started working on this issue_

**Comment by meodai** [comment]
whaaat?! Noooooo but nice effort! There are plenty of other lists that are not imported yet if you want to try your luck on an other one. It would be especially interesting to know if there was a cool way to import the diffs from the wikipedia color name page from time to time. thanks a lot for your time! I appreciate your contribution!
