### ISSUE TITLE
Visualization in README is broken

### ISSUE THREAD

**Issue by csandman** [meodai/color-names#69]
### Problem

The [Color distribution](https://codepen.io/meodai/full/zdgXJj/) codepen link in the README appears to be broken.  When I load it, I am met with a blank screen:

![image](https://user-images.githubusercontent.com/9214195/72637505-7b1d8600-392f-11ea-9774-d01c83a2a795.png)

And the following error in the console:

```
OrbitControls.js:84 Uncaught TypeError: Cannot read property 'ROTATE' of undefined
    at new THREE.OrbitControls (OrbitControls.js:84)
    at init (pen.js:180)
    at pen.js:57
```

### Solution

From [this post](https://discourse.threejs.org/t/recent-change-to-orbitcontrols-breaks-some-projects/8780) I found that it's due to a version mismatch between the orbit controls and the three.js library.  Updating the import link for three.js to the newest version fixed the problem.

```
https://cdnjs.cloudflare.com/ajax/libs/three.js/110/three.min.js
```

And [here](https://codepen.io/CSandman/pen/KKwGWKE) you can see a working version.

I'd submit a pull request but seeing as this code isn't in the repository itself, I cannot! So hopefully this is good enough 😄

**Comment by csandman** [comment]
Also, I just wanted to let you know that I'm a huge fan of this package!  I've been using it in my side project [Shade Generator](https://www.shadegenerator.com/) since very early on and it really adds an interesting touch.

**Comment by meodai** [comment]
@csandman hey! Thanks for reporting this. But it still works for me. Can you tell me in what browser you had/have this issue in?

**Comment by csandman** [comment]
@meodai I'm currently getting the issue in Chrome v.79.0.3945.117 on a windows 10 machine.

I just tried with Firefox 72.0.1 and its not working there either but with a different error:

```
TypeError: THREE.TOUCH is undefined
```

However, the same change fixes it here.  I'm not really sure why its not working for me but is working for you.

**Comment by meodai** [comment]
@csandman I did test it out on windows 10 with the latest chrome & FF everything worked fine. Let's close that for now. I will add it to the project some day anyway. Thanks for reporting it.
