### ISSUE TITLE
Add diamondvogel colors

### ISSUE THREAD

**Issue by meodai** [meodai/color-names#74]
https://www.diamondvogel.com/colorfinder

**Comment by Filippo-B** [comment]
Hi! I’d love to take care of this. Just have a question: if a color has the same hex of an existing color, is it acceptable to change it slightly, in order to keep the name? Thanks.

**Comment by meodai** [comment]
Hello Filippo. Yes, in fact there are already some tools that will help you do so `https://github.com/meodai/color-names/tree/master/scripts/tools`.

**Comment by meodai** [comment]
Please also make sure the names follow our contribution guidelines: https://github.com/meodai/color-names/blob/master/CONTRIBUTING.md this might help; https://github.com/meodai/color-names/blob/master/scripts/tools/filterUniques.js#L16

**Comment by meodai** [comment]
@Filippo-B I just checked, looks like most are already in. Let me know if you need some help automating something

**Comment by meodai** [comment]
@Filippo-B thanks so much

**Comment by Filippo-B** [comment]
Thank you for your patience. Sorry if I haven't been careful enough.

**Comment by meodai** [comment]
@Filippo-B you could not have possible known! It was very useful that you did! thanks
