### ISSUE TITLE
API endpoint to search for colors by name

### ISSUE THREAD

**Issue by joinemm** [meodai/color-names#82]
Would it be possible to add an endpoint to the api to search for colors by name instead of hex?

**Comment by meodai** [comment]
@joinemm thanks for your request. I'm not sure what the use case for it would be. Also it would need a bit of rework of the API script, could go into V2.

**Comment by joinemm** [comment]
Use case would be to let users search for possible colors, or one they know the name of. Not really too important but something that would be cool to have. Probably not worth reworking the API for but yeah for V2 something to consider.

**Comment by meodai** [comment]
I'll keep it open as a feature request for the V2 API then! Thanks @joinemm

**Comment by meodai** [comment]
@joinemm I added the feature. It is now possible to search a color by its name:
[https://api.color.pizza/v1/names/red](https://api.color.pizza/v1/names/red)
can also return only the good names:
[https://api.color.pizza/v1/names/red?goodnamesonly=true](https://api.color.pizza/v1/names/red?goodnamesonly=true)

alternatively it can be used like so:
[https://api.color.pizza/v1/names/?name=red](https://api.color.pizza/v1/names/?name=red)

I did not add it to the readme yet. Feel free to do so and close the issue when you did! 

Happy x-mas ;)

**Comment by joinemm** [comment]
@meodai oh amazing! This is great. I'll see what I can add to the readme and send a PR

**Comment by meodai** [comment]
thanks! Resolved in c8baa93ebf0d9433f5c0ce339d1cf0e979dc56f2
