### ISSUE TITLE
Bad color name - Image Tone?

### ISSUE THREAD

**Issue by StevePaget** [meodai/color-names#83]
I'm not sure Image Tone and Light Image Tone really work as colour names. They're a bit too close to just saying "Colour".

I mean, they're not very exciting colours, but surely they deserve a better name.

**Comment by meodai** [comment]
Do you have some exmaples?

**Comment by StevePaget** [comment]
I'd say:

Image Tone -> Gravestone
Light Image Tone -> Whomp Grey

Any good?

**Comment by meodai** [comment]
Oh I misunderstood your first request :D Of course let's fix that.

The next release will incorporate your fix! Thanks for reporting

**Comment by StevePaget** [comment]
Thanks!

Incidentally, the link in the repo Readme that says 

**Color Name Submission
via form / or twitter** 

The twitter link doesn't lead to twitter. It leads to the CodePen site.
