### ISSUE TITLE
Download and Cloning on Mac environment to create a local application for Windows

### ISSUE THREAD

**Issue by fgsvictory** [meodai/color-names#91]
Hi,

Always Victory!!!

I trying to follow the instructions here presented, but I didn't have any success. My issue is that I want to download (zip file) this GitHub and create a local application for my personal work. 

When I try to use the Terminal of my Mac to run it as was shown here I didn't have any success then I try to clone it but I had the same problem. 

Is there any tutorial video or more information elsewhere I can follow to create this local application?

Thanks in advance.

Regards,
Frederico

**Comment by meodai** [comment]
Hello @fgsvictory, thank you for creating an issue. 
I am not sure what you are trying to achieve. The repository only contains a list of color names in different formats. You can probably open the CSV file contained in the `src` folder in excel: https://github.com/meodai/color-names/blob/master/src/colornames.csv 

I don't know of any windows or osx app that uses the list. There are plenty of terminal tools using it, but they don't come with this repository.

- https://github.com/shariati/cherangi 
- https://github.com/adamwatters/vscode-color-pick
- https://github.com/igorokb/get-color-name

**Comment by meodai** [comment]
@fgsvictory made a excel export for you
[Color Names for https___github.com_meodai_color-names_.xlsx](https://github.com/meodai/color-names/files/5164669/Color.Names.for.https___github.com_meodai_color-names_.xlsx)

**Comment by meodai** [comment]
@fgsvictory I am closing this. Il create a new issue if needed once I understand what you are trying to do,
